Add implementation of the quicksort algorithm
debdutgoswami/sorting-visualizer pull request #3
Opened 2020-10-04 19:10 UTC by ChristosDeretzis

2020-10-04 20:02 UTC, debdutgoswami requested changes

2020-10-04 20:02 UTC, debdutgoswami commented on sorting_visualizer/sort.py
> +def quicksort(A, low, high):
This won't work. You need to create generators using `yield`. Also, note that you can only use iterative solutions. Recursive solutions don't exactly return generator objects at each iteration.

2020-10-07 18:27 UTC, debdutgoswami requested changes
Fixing this should be fine and ready to be merged. Great job.

2020-10-07 18:27 UTC, debdutgoswami commented on sorting_visualizer/sort.py
> +    yield A
This should be inside the while loop.

2020-10-07 18:40 UTC, ChristosDeretzis commented on sorting_visualizer/sort.py
> +    yield A
I just fixed that

2020-10-07 18:54 UTC, debdutgoswami approved these changes

2020-10-07 18:55 UTC, merged

2020-10-07 18:55 UTC, debdutgoswami commented
Thanks for your contribution.